name: Deploy_to_prod

on:
  pull_request:
    types:
      - closed
    branches:
      - "main"
    paths-ignore:
      - 'Documentation/**'
      - 'README.md'

    
permissions:
  contents: read

jobs:
  build_and_deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"   
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install Dependencies using Poetry
      run: |
          poetry install
    - name: Initialize test database
      run: poetry run invoke init-db ${{ secrets.DATABASE_URI }}
    - name: Coverage report
      run: |
          poetry run coverage run --branch -m pytest
          poetry run coverage xml
      env:
        DATABASE_URI: ${{ secrets.DATABASE_URI }}
        ENVIRONMENT: "test"  
    - name: Coverage report to Codecov
      uses: codecov/codecov-action@v2
    - name: deploy
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "superadmin3000"
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        usedocker: true