name: Deploy_to_prod

on:
  pull_request:
    branches: [ "main" ]  
    paths-ignore:
      - 'docs/**'
      - 'Documentation/**'
      - 'README.md'

    
permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/test_build.yml
  heroku:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "superadmin3000"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
