# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: 
    - main
# Branches can be added as follows:
#   - olenleo-actions    
    
  pull_request:
    branches: [ "main" ]
    
  workflow_call:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"   
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      
    # Add dependencies with 'poetry add <dependency>'
    # For example:
    #  run: |
    #    poetry add a_dependency
    #    poetry install
    
    - name: Install Dependencies using Poetry
      run: |
          poetry install
      
#    - name: Test with pytest
#      run: |
#        pytest
