# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: 
    - main
# Brances can be added as follows:
#   - olenleo-actions
    
    
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"   
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      
    # Add dependencies with 'poetry add <dependency>'
    # For example:
    #  run: |
    #    poetry add a_dependency
    #    poetry install
    
    - name: Install Dependencies using Poetry
      run: |
          poetry install
      
#    - name: Test with pytest
#      run: |
#        pytest

  heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "superadmin3000" #Must be unique in Heroku
          heroku_email: "me@juan.fi"
          usedocker: true

