# This workflow will install Python dependencies, run tests and lint with a single version of Python. I is triggered on pull request to main branch.
# The workflow is reusable and can be called from other workflows.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request:
    branches: [ "main" ]  
    paths-ignore:
      - 'docs/**'
      - 'Documentation/**'
      - 'README.md'
  # make workflow reusable
  workflow_call:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"   
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      
    # Add dependencies with 'poetry add <dependency>'
    # For example:
    #  run: |
    #    poetry add a_dependency
    #    poetry install
    
    - name: Install Dependencies using Poetry
      run: |
          poetry install

    - name: Run style checks
      run: |
          poetry run invoke lint
          
    - name: Run unit tests
      run: |
          poetry run invoke tests
          
    - name: Coverage report
      run: poetry run coverage xml
    - name: Coverage report to Codecov
      uses: codecov/codecov-action@v2

    - name: Setup chromedriver
      uses: nanasess/setup-chromedriver@master
    - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    - name: Run robot tests
      run: bash run_robot_tests.sh
      env:
        ENVIRONMENT: local
        GOOGLE_CLIENT_ID: fakegoogleid
        SECRET_KEY: secretkey
        
